### PR TITLE
RHF with options!

### PR DESCRIPTION
**Pull request by dsirianni**
RHF implementation with options for:
1) DF or PK integrals
2) BLAS or einsum for tensors
3) DIIS or no DIIS -- and what iteration to turn it on

### CODE REVIEW

**Comment by LACunha** [comment]
Is your code with BLAS actually faster than with einsum? I'm just wondering because mine doesn't seem to be that good with BLAS :-/ (comparing only the DF-SCF)

**Comment by dgasmith** [comment]
Did you guys install Conda accelerate? On my phone but worth googling this. Without a high end blas library it won't be faster.

**Comment by LACunha** [comment]
@dgasmith : Yep, I already had Conda accelerate on my computer. 

I've changed my code a little bit to avoid copying variables, but it is still slower using BLAS (comparing only the SCF iterations time). Also, it is a lot slower than Dom's ( ~ 1.7 s slower), even though we're doing almost the same thing in my modified version. I'm using cc-pV5Z to run my tests.

One of the differences is that I'm actually calling Psi4 functions to get the variables, instead of defining new variables for my options (using psi4.get_global_options(...)). How costly is this procedure?

**Comment by dgasmith** [comment]
Those operations are very cheap. I think its time to start talking about processor specific [instruction sets](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) and how the effect timings. Another thing to consider is to time _only_ the JK builds. We are building the DF tensors very inefficiently at current.

**Comment by LACunha** [comment]
It seems that the expression that I'm using to build my zeta for the K object is the main bottleneck here. Using the same 

`K=np.dot(np.einsum('Pup->uPp',zeta).reshape(main_nbf,1),np.einsum('Pvp->Ppv',zeta).reshape(-1,main_nbf))`

and

1)`zeta = np.dot(Cocc.T, Qpq.reshape(-1, main_nbf).T).T.reshape(aux_nbf, main_nbf, ndocc)`. The SCF iteration time is 2.876 s and the time to build zeta is 0.059189 s (This one is similar to Dom's implementation and takes almost the same time. It was just modified to fit my K object)

2) `zeta = np.dot(Qpq.reshape(-1,main_nbf),Cocc).reshape(aux_nbf,main_nbf,ndocc)`. The SCF iteration time is 4.830 s and the time to build zeta is 0.231438 s (This is my original implementation)

**Comment by dgasmith** [comment]
Hmm thats interesting. On my laptop they take roughly the same amount of time. To me this suggest an inefficient BLAS library as the bottom case is the harder of the two.

Please run `numpy.show_config()` and make sure that there are items that have `mkl` in them.

**Pull request merged**
